### ISSUE TITLE
Resize & Compress/Fix all Images to PNG, 150x150

### ISSUE THREAD

**Issue by aerofusionyt** [NetskyCommunity/NetskyWebsite#23]
Doing this to increase load times and consistency.
@mrdnomaid you seem to be good at this.

I got reports of the images being slow due to them being unoptimized, so I trust you can fix that. Otherwise, I will do it soon.

Note: You'll have to change the images on the index.html to .png.

**Comment by mrdnomaid** [comment]
Done - https://github.com/NetskyCommunity/NetskyWebsite/commit/23109339a2acfaff5612f741124083253ec92b5f
